env:
  - tf_version=0.11.10

sudo: required

language: bash

before_install:
  - wget https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip
  - gem install travis

script:
  - shellcheck modules/kubernetes/scripts/* # Validating BASH
  - shellcheck utilities/*.sh # Validating BASH
  - travis lint # Linting travis file
  - cd examples
  - terraform init
  - terraform validate # Validating Terraform

notifications:
  email:
    recipients:
      - fabrizio.sabatini.it@gmail.it
      - stopcontinentaldrift@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
